### ISSUE TITLE
Return messages segments if messages array not provided

### ISSUE THREAD

**Issue by pinguinjkeke** [franzose/kontrolio#6]
Thank you for the great package (I'm so surprised it has so little downloads count).

It would be great to provide a little future.

I want to leave messages array empty and receive the output like:
```
[
   'email' => [
        'email.email',
        'email.not_blank'
    ]
]
```
Then I'll pass this array to my translator, instead of creating array by hands every time.

**Comment by franzose** [comment]
@pinguinjkeke Hi, you should get the functionality soon as I has just implemented it!

**Comment by pinguinjkeke** [comment]
@franzose wow, man, that speed! Thank you a lot.
Will it be in the release? Or should i run from master repo?

**Comment by franzose** [comment]
@pinguinjkeke I'm drafting a new release, wait a few minutes, please :)
